
git:
  quiet: true

language: rust

cache:
  cargo

rust:
  - 1.36.0

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx

install:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]
    then
      # https://packages.ubuntu.com/bionic/libsdl2-dev
      sudo apt-get -qq install libsdl2-dev
    else
      # https://formulae.brew.sh/formula/sdl2#default
      brew update
      brew install sdl2
    fi
  # Run these to confirm that the SDL2 installation is working
  - sdl2-config --version
  - sdl2-config --cflags
  - sdl2-config --libs
  - sdl2-config --static-libs

script:
  # dynamic
  - cargo build
  - cargo test
  - cargo build --features="extern_crate_raw_window_handle"
  - cargo clean
  # static
  - cargo build --no-default-features --features="static_link"
  - cargo test --no-default-features --features="static_link" -- --test-threads=1
  - cargo clean
