
os: Visual Studio 2015

environment:
  # The pre-built SDL2 files that we have are for MSVC only.
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup component add clippy
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo clippy -- -D warnings
  - cargo build
  - cargo test

