[package]
name = "beryllium"
description = "An opinionated set of high level wrappers for the `fermium` SDL2 bindings."
repository = "https://github.com/Lokathor/beryllium"
version = "0.0.9"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"

[dependencies]
fermium = "0.0.15"
phantom-fields = "^0.1.2"
libc = "0.2"

[dev-dependencies]
gl = "0.12"
glium = "0.25"
ash = "0.29"

[badges]
appveyor = { repository = "Lokathor/beryllium" }
travis-ci = { repository = "Lokathor/beryllium" }
