[package]
name = "beryllium"
description = "Opinionated, high-level wrappers for `fermium`."
repository = "https://github.com/Lokathor/beryllium"
version = "0.4.0-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
keywords = ["SDL2"]
categories = ["api-bindings", "multimedia", "no-std"]

[features]
default = []
dynamic_link = ["fermium/dynamic_link"]
std = []

[dependencies]
fermium = { version = "20016", default-features = false }
zstring = "0.0.3"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc = "0.2"

[dev-dependencies]
glitz = "0.1"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
