[package]
name = "beryllium"
description = "An opinionated set of high level wrappers for the `fermium` SDL2 bindings."
repository = "https://github.com/Lokathor/beryllium"
version = "0.1.1"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"
keywords = ["sdl2"]
categories = ["api-bindings", "multimedia", "game-engines", "no-std"]

# This forces docs.rs to build us on windows, which has the simplest build for
# docs.rs to perform.
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[dependencies]
fermium = { version = "^0.1.2", default-features = false }
phantom-fields = "^0.1.2"
raw-window-handle = "0.3"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc = "0.2.6"

[dev-dependencies]
gl = "0.12"
glium = "0.25"
ash = "0.29"

[features]
default = ["link_dynamic"]
link_dynamic = ["fermium/link_dynamic"]
link_static = ["fermium/link_static"]
impl_global_alloc = []

[badges]
appveyor = { repository = "Lokathor/beryllium" }
travis-ci = { repository = "Lokathor/beryllium" }
