[package]
name = "beryllium"
description = "An opinionated set of high level wrappers for the `fermium` SDL2 bindings."
repository = "https://github.com/Lokathor/beryllium"
version = "0.2.0-alpha.1"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"
keywords = ["SDL2"]
categories = ["api-bindings", "multimedia", "game-engines", "no-std"]

# This forces docs.rs to build us on windows, which has the simplest build for
# docs.rs to perform.
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[features]
default = ["link_dynamic", "extern_crate_raw_window_handle"]
link_dynamic = ["fermium/link_dynamic"]
link_static = ["fermium/link_static"]
extern_crate_raw_window_handle = ["raw-window-handle"]
#impl_global_alloc = []

[dependencies]
fermium = { version = "0.1", default-features = false }
raw-window-handle = { version = "0.3", optional = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc = "0.2"

[badges]
appveyor = { repository = "Lokathor/beryllium" }
travis-ci = { repository = "Lokathor/beryllium" }
