[package]
name = "beryllium"
description = "Opinionated, high-level wrappers for `fermium`."
repository = "https://github.com/Lokathor/beryllium"
version = "0.6.0"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
keywords = ["SDL2"]
categories = ["api-bindings", "multimedia", "no-std"]

[features]
default = ["std"]
dynamic_link = ["fermium/dynamic_link"]
std = []

[dependencies]
fermium = { version = "20016", default-features = false }
zstring = "0.0.3"
tinyvec = "1"
bytemuck = "1"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc = "0.2" # needed to verify that we're on the main thread.

[dev-dependencies]
glitz = {version = "0.2", features=["std"]}
#ash = "0.33"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
