name: Rust

on:
  push: {}
  pull_request: {}

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - { rust: stable, os: macos-latest }
        - { rust: stable, os: windows-latest }
        - { rust: stable, os: ubuntu-latest }

    steps:
    - uses: actions/checkout@v3
    - name: Cargo Check
      run: cargo check --features="cargo_check"
