name: Rust

on:
  push: {}
  pull_request: {}
  schedule:
    # Min Hr Day Month Weekday; so this should be 1:05am each day.
    - cron: '5 1 * * *'

jobs:
  build_test:
    runs-on: ${{ matrix.rust.os }}
    strategy:
      matrix:
        rust:
        - { toolchain: 1.48.0, os: macOS-latest, target: x86_64-apple-darwin }
        - { toolchain: 1.48.0, os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
        - { toolchain: 1.48.0, os: windows-latest, target: x86_64-pc-windows-msvc }
        - { toolchain: 1.48.0, os: windows-latest, target: i686-pc-windows-msvc }
        - { toolchain: stable, os: macOS-latest, target: x86_64-apple-darwin }
        - { toolchain: stable, os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
        - { toolchain: stable, os: windows-latest, target: x86_64-pc-windows-msvc }
        - { toolchain: stable, os: windows-latest, target: i686-pc-windows-msvc }
        - { toolchain: beta, os: macOS-latest, target: x86_64-apple-darwin }
        - { toolchain: beta, os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
        - { toolchain: beta, os: windows-latest, target: x86_64-pc-windows-msvc }
        - { toolchain: beta, os: windows-latest, target: i686-pc-windows-msvc }
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust.toolchain }}
        target:  ${{ matrix.rust.target }}
        profile: minimal
        default: true
    
    # Note(Lokathor): We don't ever need to install SDL2, it's bundled!
    
    - name: Run Tests with Static Linking (the default linking)
      uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ matrix.rust.toolchain }}
        command: test

    - name: Run Tests with Dynamic Linking
      uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ matrix.rust.toolchain }}
        command: test
        args: --features=dynamic_link
    
    - name: Check the raw-window-handle impl
      uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ matrix.rust.toolchain }}
        command: test
        args: --features=raw-window-handle
